name: Sync to private repo for Vercel deployment

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  sync:
    if: github.repository == 'ki-fa/campus-resource-manager'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to private repo
        env:
          TOKEN: ${{ secrets.PAT }}
          DEST: csus-bogar/campus-resource-manager
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add private https://x-access-token:${TOKEN}@github.com/${DEST}.git
          #rm -if .github/workflows/*
          #git add -A
          #git commit -m "Sync without workflows"
          git push private HEAD:main --force
